### ISSUE TITLE
interested in Babel plugin

### ISSUE THREAD

**Issue by tomByrer** [js-choi/proposal-smart-pipelines#13]

**Comment by js-choi** [comment]
A Babel plugin is in development in collaboration with @mAAdhaTTah. We are updating Babylon and [babel-plugin-proposal-pipeline-operator](https://github.com/babel/babel/tree/master/packages/babel-plugin-proposal-pipeline-operator). See https://github.com/babel/proposals/issues/29#issuecomment-372828328. You can track its current progress at https://github.com/js-choi/babel and https://github.com/valtech-nyc/babel.

I should link to those resources from the explainer document. I’ll close this issue when I get around to doing so.
