### ISSUE TITLE
Feature: Pipeline transforms

### ISSUE THREAD

**Issue by Sceat** [js-choi/proposal-smart-pipelines#33]
<h3 align=center>Let's go further and play with the language to parse a mapper</h3>

---

Christmas is coming.. 🙏 

## map
<img align=right src='https://user-images.githubusercontent.com/11330271/58743552-4c07e200-843c-11e9-9090-75fae9817769.png'>

```js
[1,2] ||> # + 1 |> console.log // [2,3]

const add = a => b => a + b
// bare style :)
[1,2] ||> add(1) |> console.log // [2,3]

// to
console.log([1,2].map(add(1)))
```
## filter
<img align=right src='https://user-images.githubusercontent.com/11330271/58743655-617e0b80-843e-11e9-88ac-ce69e3ac2074.png'>

```js
[1,2] <|> (# > 1) |> console.log // [2]

const above = a => b => b > a
[1,2] <|> above(1) |> console.log // [2]

// to
console.log([1,2].filter(above(1)))
```

## reduce
<img align=right src='https://user-images.githubusercontent.com/11330271/58743590-3e069100-843d-11e9-9380-c67c676fec27.png'>

```js
[1,2] <|| # + ## |> console.log // 3

const add = a => b => a + b
[1,2] <|| add |> console.log // 3

// bare bare bare
// [1,2] <|| add(#)(##) |> console.log // 3

// to
console.log([1,2].reduce((a,b) => a + b))
```

**Comment by Sceat** [comment]
some will say, but dude why not
```js
const add = (a, b) => a + b
[] |> #.reduce(add) |> console.log
```
🤔 it's a complete different style of programming, seems like some form of macro or hack instead of hardcore functional 😀

**Comment by js-choi** [comment]
Thanks for the issue; sorry about the delayed reply.

After talking more with Tab Atkins and Daniel Ehrenberg, we’ve decided to archive this proposal in favor of a [simpler Hack-pipes proposal][Hack pipes], which is a subset of this proposal.

Feel free to open a new issue in the new repository if you think it still applies.

[Hack pipes]: https://github.com/js-choi/proposal-hack-pipes/
