### ISSUE TITLE
Full bare style option

### ISSUE THREAD

**Issue by Sceat** [js-choi/proposal-smart-pipelines#34]
@js-choi at least could you allow the syntaxe with a plugin option ? it's handy and the `#` give a parsing error in prettier so we can't format our code, it should be a prettier issue but as this `#` is not 'definitive' nor pure functionnal we would have to remove it anyway when using F# pipelines or this one in pure bare style 

![image](https://user-images.githubusercontent.com/11330271/58937478-36b3f000-877b-11e9-877f-7daf71b4fed1.png)

![image](https://user-images.githubusercontent.com/11330271/58937526-521efb00-877b-11e9-88b3-31c0e72d6225.png)

**Comment by js-choi** [comment]
Thanks for the issue; sorry about the delayed reply.

After talking more with Tab Atkins and Daniel Ehrenberg, we’ve decided to archive this proposal in favor of a [simpler Hack-pipes proposal][Hack pipes], which is a subset of this proposal.

Feel free to open a new issue in the new repository if you think it still applies.

[Hack pipes]: https://github.com/js-choi/proposal-hack-pipes/
