### ISSUE TITLE
[doc bug]: 'do expression' reference links refer only to ./relations.md#do-expressions && doubled  'do expression'-block

### ISSUE THREAD

**Issue by KilianKilmister** [js-choi/proposal-smart-pipelines#36]
the readme contains 2 links labeled '`do` expressions' ([a],[b]) under [Relations to Other Works], both point to [./relations.md#do-expressions], in which there are again two links which point to the paragrapf itself

**EDIT:** turns out there actually are two seperat blocks about `do` expressions. they are pretty much redundant

[./relations.md#do-expressions]:<https://github.com/js-choi/proposal-smart-pipelines/blob/master/relations.md#do-expressions>
[Relations to Other Works]:<https://github.com/js-choi/proposal-smart-pipelines/#relations-to-other-work>
[a]:<https://github.com/js-choi/proposal-smart-pipelines/#do-expressions>
[b]:<https://github.com/js-choi/proposal-smart-pipelines/#do-expressions-1>

**Comment by js-choi** [comment]
Thanks for the issue; sorry about the delayed reply.

After talking more with Tab Atkins and Daniel Ehrenberg, we’ve decided to archive this proposal in favor of a [simpler Hack-pipes proposal][Hack pipes], which is a subset of this proposal.

Feel free to open a new issue in the new repository if you think it still applies.

[Hack pipes]: https://github.com/js-choi/proposal-hack-pipes/
