### ISSUE TITLE
Exaggeration under With No Pipelines

### ISSUE THREAD

**Issue by houghtonap** [js-choi/proposal-smart-pipelines#38]
> "Unfortunately, these deeply nested expressions often result in messy spaghetti code, due to their mixing of prefix, infix, and postfix expressions together. Writing such code requires many nested levels of indentation and parentheses. Reading such code requires checking both the left and right of each subexpression to understand its data flow."

This statement is an exaggerated view of the situation and IMHO driven by coding style rather than using simpler coding techniques that are defined in and driven by the proposal itself. For example, the following nested code, similar to the example given:

```javascript
let testDataset = [ 'abc\n', 'def\n', 'ghi\n' ] ;
async function * toLine ( iterable ) { /* implementation */ }
async function * toUpperCase ( iterable ) { /* implementation */ }
async function toLogger ( iterable ) { /* implementation */ }
await toLogger(
  toUpperCase(
    toLine(
      testDataset
    )
  )
) ;
```
can simply be re-written as:

```javascript
let testDataset = [ 'abc\n', 'def\n', 'ghi\n' ] ;
async function * toLine ( iterable ) { /* implementation */ }
async function * toUpperCase ( iterable ) { /* implementation */ }
async function toLogger ( iterable ) { /* implementation */ }
let temp = testDataset ;
temp = toLine( temp ) ;
temp = toUpperCase( temp ) ;
temp = toLogger( temp ) ;
await temp ;
```

This coding style has zero indentation, thus negating the overstatement in the proposal.

The general purpose of this proposal is to transform the result of the left expression and make it a parameter of the next function in the sequence, which is what the simpler coding style is doing:

```javascript
let testDataset = [ 'abc\n', 'def\n', 'ghi\n' ] ;
async function * toLine ( iterable ) { /* implementation */ }
async function * toUpperCase ( iterable ) { /* implementation */ }
async function toLogger ( iterable ) { /* implementation */ }
await ( 
  testDataset
  |> toLine
  |> toUpperCase
  |> toLogger
) ;
```

I put parenthesis around the proposed syntax because it is unclear what using await in this situation means, e.g., is that await testDataset (no effect) or await the whole pipeline?

**Comment by js-choi** [comment]
Thanks for the issue; sorry about the delayed reply.

After talking more with Tab Atkins and Daniel Ehrenberg, we’ve decided to archive this proposal in favor of a [simpler Hack-pipes proposal][Hack pipes], which is a subset of this proposal.

Feel free to open a new issue in the new repository if you think it still applies.

[Hack pipes]: https://github.com/js-choi/proposal-hack-pipes/
