### ISSUE TITLE
Explainer: Add goal about semantic nonambiguity

### ISSUE THREAD

**Issue by js-choi** [js-choi/proposal-smart-pipelines#6]
<del>An advantage that this proposal has is that parentheses can never change the meaning of a code without giving an early error. `x |> (await #)` is the same as `x |> await #`, and `x |> (await y)` and `x |> await y` are both early errors that require the developer to disambiguate between `x |> (await y)(#)` and `x |> await y(#)`. This should be noted in Goals and in the Motivation, Core Proposal too, as well as the [pipeline-operator wiki](https://github.com/tc39/proposal-pipeline-operator/wiki).</del>

Edit: That advantage is moot. However, this proposal still has an advantage in that it forces the writer to make explicit which of these reasonable alternatives do they mean by `x |> foo`: `x |> foo(#, y)`, `x |> foo(y, #)`, and `x |> foo(y)(#)`. This is also important, so I’m reusing this issue to track better explaining this in § Goals, in § Motivation, Core Proposal, and in the wiki. See https://github.com/js-choi/proposal-smart-pipelines/issues/2#issuecomment-373493849.

**Comment by js-choi** [comment]
This issue is moot, because Proposal 1 is stable with parentheses.
Cross-referencing from https://github.com/js-choi/proposal-smart-pipelines/issues/2#issuecomment-374019509:

> I hadn’t realized this until recently myself: `(foo.bar)(x)` retains its receiver for the same reason that `delete (foo.bar)` works. The [grouping operator’s evaluation algorithm](https://tc39.github.io/ecma262/#sec-grouping-operator-runtime-semantics-evaluation) does *not* apply the [GetValue abstract operation](https://tc39.github.io/ecma262/#sec-getvalue) to its subexpression’s result, even if that result is a Reference. This means that it itself may evaluate to a [Reference](https://tc39.github.io/ecma262/#sec-reference-specification-type), and this allows [function calls’ evaluation algorithm](https://tc39.github.io/ecma262/#sec-function-calls-runtime-semantics-evaluation) to use the [Reference’s base](https://tc39.github.io/ecma262/#sec-getbase).
>
> I’m really glad that this fragility problem doesn’t seem apply to Proposal 1—though it does put a lot of the burden of its being useful on @rbuckton’s partial-application proposal, which smart pipelines would also subsume with a similar amount of syntactic complexity. Smart pipelines also try hard to prevent visual ambiguity, requiring `x |> await o.p` to be distinguished as `x |> await o.p(y, #)`, `x |> await o.p(#, y)`, `x |> await o.p(y)(#)`, `x |> (await o.p(y))(#)`, `x |> (await o.p)(#)` or `x |> await #`, all of which are reasonable interpretations.

| Proposal | Original/minimal proposal (F# only) | Proposal 1 (F# only + await) | Proposal 4 ([smart pipelines](https://github.com/js-choi/proposal-smart-pipelines/)) |
| --- | --- | --- | --- |
| `x \|> o.p` | `o.p(x)` | `o.p(x)` | `o.p(x)` |
| `x \|> (o.p)` | `o.p(x)` | `o.p(x)` | Early Syntax Error: Topic-style pipeline needs topic reference `#`. Use<br> `x \|> o.p` or<br>`x \|> (o.p)(#)`. |
| `x \|> o.p(y)` | `o.p(x)(y)` | `o.p(x)(y)` | Early Syntax Error: Topic-style pipeline needs topic reference `#`. Use<br> `x \|> f(y, #)`,<br>`x \|> f(#, y)`, or<br>`x \|> f(y)(#)`. |
| `x \|> await` | Early Syntax Error: `await` not supported | `await x`: await the value `x` | Early Syntax Error: Topic-style pipeline needs topic reference `#`. Use<br> `x \|> await #`. |
| `x \|> (await)` | `(await)(x)` – Syntax Error: Unexpected `)` | `(await)(x)` – Syntax Error: Unexpected `)` | Early Syntax Error: Topic-style pipeline needs topic reference `#`. Use<br> `x \|> await #`. |
| `x \|> await o.p` | Syntax Error: `await` not supported | `(await x) o.p` – Syntax Error: Unexpected `o.p` | **Without Feature BA**:<br>Early Syntax Error: Topic-style pipeline needs topic reference `#`. Use<br> `x \|> await o.p(#)` or<br>`x \|> (await o.p)(#)`.<br>**With Feature BA**:<br>`await o.p(x)` |
| `x \|> (await o.p)` | Syntax Error: `await` not supported | `(await o.p)(x)` | Early Syntax Error: Topic-style pipeline needs topic reference `#`. Use<br> `x \|> await o.p(#)` or<br>`x \|> (await o.p)(#)`. |
| `x \|> await o.p(y)` | Syntax Error: `await` not supported | `(await o.p(y))(x)` | Early Syntax Error: Topic-style pipeline needs topic reference `#`. Use<br> `x \|> await o.p(y, #)`,<br>`x \|> await o.p(#, y)`,<br>`x \|> await o.p(y)(#)`,<br>`x \|> (await o.p(y))(#)`,<br>`x \|> (await o.p)(#)`, or<br>`x \|> await #`. |
| `x \|> new` | Syntax Error | Syntax Error | Syntax Error |
| `x \|> (new)` | `(new)(x)` – Syntax Error: Unexpected `)` | `(new)(x)` – Syntax Error: Unexpected `)` | `(new)(x)` – Syntax Error: Unexpected `)` |
| `x \|> new o.p` | TypeError: `new o.p` is not a function; it is an instance of `o.p`. | TypeError: `new o.p` is not a function; it is an instance of `o.p`. | **Without Feature BC**:<br>Early Syntax Error: Topic-style pipeline needs topic reference `#`. Use<br> `x \|> await o.p(#)` or<br>`x \|> (await o.p)(#)`.<br>**With Feature BC**:<br>`new o.p(x)` |
| `x \|> (new o.p)` | TypeError: `(new o.p)` is not a function; it is an instance of `o.p`. | TypeError: `(new o.p)` is not a function; it is an instance of `o.p`. | Early Syntax Error: Topic-style pipeline needs topic reference `#`. Use<br> `x \|> await o.p(#)` or<br>`x \|> (await o.p)(#)`. |
| `x \|> new o.p(y)` | TypeError: `(new o.p)` is not a function; it is an instance of `o.p`. | TypeError: `(new o.p)` is not a function; it is an instance of `o.p`. | Early Syntax Error: Topic-style pipeline needs topic reference `#`. Use<br> `x \|> new o.p(y, #)`,<br>`x \|> new o.p(#, y)`,<br>`x \|> new o.p(y)(#)`,<br>`x \|> (new o.p(y))(#)`,<br>`x \|> (new o.p)(#)`, or<br>`x \|> new #`. |
| `x \|> () => y` | Syntax Error: Unexpected `=>`. Use<br> `x \|> (() => y)` instead | Undecided | Early Syntax Error: Unexpected `=>`. Use<br> `x \|> (() => y)(#)` or<br>`x \|> (() => #)`. |
| `x \|> (() => y)` | `(() => y)(x)` | `(() => y)(x)` | Early Syntax Error: Topic-style pipeline needs topic reference `#`. Use<br> `x \|> (() => y)(#)` or<br>`x \|> (() => #)`. |

***

However, this proposal still has an advantage in that it forces the writer to make explicit which of these reasonable alternatives do they mean by `x |> foo`: `x |> foo(#, y)`, `x |> foo(y, #)`, and `x |> foo(y)(#)`. This is also important, so I’m reusing this issue to track better explaining this in § Goals, in § Motivation, Core Proposal, and in the wiki. See https://github.com/js-choi/proposal-smart-pipelines/issues/2#issuecomment-373493849.

**Comment by mAAdhaTTah** [comment]
In F#, `x |> await o.p` is a `SyntaxError`. It'll require parentheses to achieve the stated semantics.

**Comment by js-choi** [comment]
@mAAdhaTTah: Ah. Why is it an error? The syntax of `x |> await o.p` intuitively groups as `x |> (await o.p)`, and `await (o.p(x))` and `(await o.p)(x)` both seem like reasonable interpretations of that to me.

**Comment by mAAdhaTTah** [comment]
That ambiguity is part of the reason; `x |> await` is the whole expression, so `o.p` is a separate expression, and an expression next to an expression is a SyntaxError.

That's what I would like it to be, anyway. I'm drawing that interpretation from here: https://github.com/tc39/proposal-pipeline-operator/pull/85

**Comment by js-choi** [comment]
Good to know; thanks! I will update the wiki table later today.
